### ISSUE TITLE
Linux first run: lots of warnings

### ISSUE THREAD

**Issue by jidanni** [Stellarium/stellarium-data#10]
I just want to mention that on Debian I installed
Package: stellarium-data Version: 23.4-2
and started it and it worked but there were lots of warnings:
```
Satellite has invalid orbit: "ZDPS 2A" "40901"
Satellite has invalid orbit: "PEGASUS" "42784"
Satellite has invalid orbit: "VENTA 1" "42791"
Satellite has invalid orbit: "NUSAT-4 (ADA)" "43195"
Satellite has invalid orbit: "NUSAT-5 (MARYAM)" "43204"
Satellite has invalid orbit: "STARLINK-1119" "44928"

**Comment by gzotti** [comment]
Sure. This flood of warnings means Stellarium has not been run in a few weeks, and therefore some "Satellites have invalid orbits" and will be removed or need updates. This is intended behaviour.

**Comment by jidanni** [comment]
Maybe such a message could be added to the top of the rest.
