### ISSUE TITLE
Is extend data catalog.txt published?

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium-data#3]
I don't know how to decode extended data file.

**Comment by alex-w** [comment]
All source data for Stellarium’ DSO catalog are published. But, please, don’t touch it at the moment, because I’m in the process of updating the code of catalog generator (adding the data and code for incorporating few new catalogs into our DSO catalog).

**Comment by nem64** [comment]
Hi! Any progress on this? We're planning to use stellarium's catalogue on a telescope control website.

Our solution right now is to use Stellarium on an X virtual frame buffer and use the web api to pull RA/Dec. It's a bit of a hack and it takes a lot of resources so i figured why not take the database and convert it to a NoSQL/SQL database and pull data from there instead.

Is there any licensing/technical issue with doing that? Thanks.

**Comment by gzotti** [comment]
Sounds like the worst practice hack to control a telescope. 
Why not access any other database out there meant to be accessed remotely, or just be downloaded for your own use?

**Comment by nem64** [comment]
Which is exactly why i called it a hack and why we need a better solution! We like stellarium's database, a lot. So that's why i was asking, but that could also work.. Thanks!

**Comment by alex-w** [comment]
Our DSO catalog based on data from SIMBAD and NED + some fixes from other sources (scientific papers and 2-3 popular datasource for Messier and Caldwell catalogs).
