### ISSUE TITLE
DSOCat on website

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium-data#6]
@alex-w  
Some files in http://astro.altspu.ru/~aw/stellarium/DSOCat/ are unavailable to download, could you repair them?

**Comment by alex-w** [comment]
Please check it

**Comment by ultrapre** [comment]
BarnardCat_tabbed.txt is not online.

**Comment by alex-w** [comment]
Damn! I've accidentally delete this file some time ago and now I should re-pack DSO catalog to restore fixes for opacity of Barnard's objects. :(

Thanks for notification (the file is restored)!

**Comment by ultrapre** [comment]
Now all fine thanks
